-- Using the hash generated by your app
UPDATE [dbo].[Users] 
SET PasswordHash = '$2a$11$V2rr9n6M7Q6OCgUnU4ezZOhNi8DB3EJvZNB1zg1LkHRQzFVH1r02.', 
    IsActive = 1, 
    Role = 'Admin' 
WHERE Username = 'admin';

-- Also update the rider you already have
UPDATE [dbo].[Users] 
SET PasswordHash = '$2a$11$V2rr9n6M7Q6OCgUnU4ezZOhNi8DB3EJvZNB1zg1LkHRQzFVH1r02.', 
    IsActive = 1 
WHERE Username = 'rider1';